# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.CharField(default=' ', max_length=200)),
                ('date', models.DateField(default=b'2018-12-27')),
                ('time', models.TimeField(default=b'20:46')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=50)),
                ('phone', models.CharField(default='+237', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('date_added', models.DateField(default=b'2018-12-27')),
                ('time_added', models.TimeField(default=b'20:46')),
                ('profile_pic', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='user', to='pages.UserInfo'),
        ),
    ]
