# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20181227_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=b'2018-12-28'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=b'11:22'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_added',
            field=models.DateField(default=b'2018-12-28'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time_added',
            field=models.TimeField(default=b'11:22'),
        ),
    ]
