# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20181230_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(default=b'2019-01-01')),
                ('time', models.TimeField(default=b'18:57')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=b'2019-01-01'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default=b'18:57'),
        ),
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateField(default=b'2019-01-01'),
        ),
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.TimeField(default=b'18:57'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=b'2019-01-01'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=b'18:57'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_added',
            field=models.DateField(default=b'2019-01-01'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time_added',
            field=models.TimeField(default=b'18:57'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='pages.UserInfo'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='pages.UserInfo'),
        ),
    ]
