# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20190101_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=b'2019-01-03'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default=b'23:06'),
        ),
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateField(default=b'2019-01-03'),
        ),
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.TimeField(default=b'23:06'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=b'2019-01-03'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=b'23:06'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=b'2019-01-03'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=b'23:06'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_added',
            field=models.DateField(default=b'2019-01-03'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time_added',
            field=models.TimeField(default=b'23:06'),
        ),
        migrations.AddField(
            model_name='adress',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='pages.UserInfo'),
        ),
        migrations.AddField(
            model_name='adress',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='pages.UserInfo'),
        ),
        migrations.AddField(
            model_name='message',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='pages.Adress'),
            preserve_default=False,
        ),
    ]
