# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-10 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20190126_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(default=b'2019-02-10'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.TimeField(default=b'22:19'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=b'2019-02-10'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default=b'22:19'),
        ),
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateField(default=b'2019-02-10'),
        ),
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.TimeField(default=b'22:19'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=b'2019-02-10'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=b'22:19'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_added',
            field=models.DateField(default=b'2019-02-10'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time_added',
            field=models.TimeField(default=b'22:19'),
        ),
    ]
