# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-11 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20190210_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='pages.UserInfo'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='pages.UserInfo'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(default=b'2019-02-11'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.TimeField(default=b'23:00'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=b'2019-02-11'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default=b'23:00'),
        ),
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateField(default=b'2019-02-11'),
        ),
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.TimeField(default=b'23:00'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=b'2019-02-11'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=b'23:00'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_added',
            field=models.DateField(default=b'2019-02-11'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time_added',
            field=models.TimeField(default=b'23:00'),
        ),
    ]
